###
## Configuration
###

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

# Site Info
title: Tiffany Yeung
description: "I'm a software developer with a passion for UI & UX design, and a Computer Science student at the University of Waterloo."

keywords: tiffany,yeung,designer,developer,writer,computer,hire,freelance,web,software,design,development,dev,user,interface,experience,ui,ux,interaction,portfolio,linkedin,github,medium,blog,dribble,dribbble,adobe,sketch,illustration,animation,graphic,creative,art,visual,university,waterloo,uwaterloo,cs,computer,science,software

url: https://tiffanynwyeung.com
baseurl: ""

favicon: /assets/img/favicon.png

# Assets
sass:
 sass_dir: assets/stylesheets/_scss
 style: :compressed

autoprefixer:
  browsers:
    - last 5 versions

# Other
username: tiffanynwyeung
analytics: UA-72274516-1
google_site_verification: J_838pJ1ZyEqHVPx1U1q2WtzDRecA5cz7V6UVkUCf2c
