#
# Configuration
#

# Dependencies
gems:
  - jekyll-sitemap

# Site Meta
name: Tiffany Yeung

description: Tiffany Yeung is a freelance web developer and Computer Science student at the University of Waterloo, always eager to grow, learn, and build.
keywords: Tiffany, Yeung, Tiffany Yeung, university, waterloo, uwaterloo, cs, computer, science, software, web, design, web design, development, web development, web dev, user, interface, user interface, experience, user experience, ui, ux

url: http://tiffanynwyeung.com
baseurl: ""

# Site Content
tagline: Writer. Designer. Developer.

# Assets
sass:
  sass_dir: assets/stylesheets/_scss
  style: :compressed

# Other
social_media_username: tiffanynwyeung
google_analytics: UA-72274516-1
